#!/bin/bash

sudo apt install -y acl 
sudo apt install -y aria2 
sudo apt install -y autoconf 
sudo apt install -y automake 
sudo apt install -y binutils 
sudo apt install -y bison 
sudo apt install -y brotli 
sudo apt install -y bzip2 
sudo apt install -y coreutils 
sudo apt install -y curl 
sudo apt install -y dbus 
sudo apt install -y dnsutils 
sudo apt install -y dpkg 
sudo apt install -y dpkg-dev 
sudo apt install -y fakeroot 
sudo apt install -y file 
sudo apt install -y findutils 
sudo apt install -y flex 
sudo apt install -y fonts-noto-color-emoji 
sudo apt install -y ftp 
sudo apt install -y g++ 
sudo apt install -y gcc 
sudo apt install -y gdebi 
sudo apt install -y gnupg2 
sudo apt install -y haveged 
sudo apt install -y imagemagick 
sudo apt install -y iproute2 
sudo apt install -y iputils-ping 
